---
title: 'Camera Setup and Acquisition'
teaching: 15
exercises: 0
---


## Multiple-shot rotating (Pano Kit) with DSLR camera setup and acquisition

When using this method  we should follow these specific steps:

1. Position the tripod at the point where you want to take the photographs and make sure is levelled with the bubble.

2. Mount the [rotating (mount) mechanism](https://www.manfrotto.com/global/move-quick-release-system-mvaqr/) on the tripod. The mount can be motorized and operated with a remote or with a specialised app.

3. Mount the camera on top of the rotating mount and turn it on.

4. Turn your camera in portrait mode. This is ideal when shooting spherical panoramas because of the extended vertical coverage.

5. Set the camera to manual focus so that it does not 
change between different shots. 
For instance, try to focus to infinity if your 
lens permits such a function. 
To increase Focal length try to use high f-stop numbers, 
especially if you are shooting outside in good light conditions.

6. Adjust the light settings for acquiring well-lighted photographs. [This guideline](https://capturetheatlas.com/camera-settings/) contains additional advice.

7. Start shooting by rotating the camera at a minimum 60-degree angle, depending
on the focal length of your lens. Please refer to the [previous section](difference-between-techniques.Rmd) to check the amount of pictures to be taken.

8. To speed up the process you can use a [motorized camera mount](https://www.manfrotto.com/global/genie-ii-pan-tilt-sy0031-0001/) synchronized with the timer of the camera. In this case:

  - Set up the number of photographs to be taken on your camera.
  
  - Set up the interval time on your rotating mount.
  
  - Start the process.
  

Here is a comprehensive video of the whole process:

<iframe width="560" height="315" src="https://www.youtube.com/embed/7dSl5h0OVjA?si=4AvLjWDz0IXgaq2p" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> 

How to shoot 360 panoramas with a DSLR, under [Metareal](https://www.metareal.com/), via [YouTube](https://www.youtube.com/watch?v=7dSl5h0OVjA) 


\ 

Using a compact camera or a mobile phone to shoot spherical panorama photographs is slightly different than using a DSLR or a specialized 360 camera.
You will need a mobile phone mount like the [monfrotto](https://www.manfrotto.com/global/pixi-pano360-remotely-controlled-motorized-head-mhpixi360/).

<!--
### Compact cameras and mobile phones 
1. Position the tripod at the point where you want to take the photographs and make sure is leveled with the bubble.

2. Mount the [rotating (mount) mechanism](https://www.manfrotto.com/global/move-quick-release-system-mvaqr/) on the tripod. The mount can be motorized and operated with a remote or with a specialised app.

3. Mount the camera or the mobile phone (with a [tripod adapter](https://www.manfrotto.com/global/products/smartphones-action-cameras-drones/smartphone-accessories/)) on top of the rotating mount and turn it on and make sure is levelled with the level function.

- Adjust the light setting on the camera or the app. Settings for acquiring well-lighted photographs are the same settings for standard DSRL cameras (although there are some limitations on compact cameras and mobile phones). You should be already familiar with these settings. If you need some help you can consult [this guideline](https://capturetheatlas.com/camera-settings/)

- Start shooting the first photograph.

- Rotate the mount at the desired angle degree (please refer to [previous section](differences-between.techniques.Rmd)) using the remote control to the next position.

- Take the next shot until completing the full 360 rotation

- To speed up the process you can use a compact camera [motorized camera mount](https://www.manfrotto.com/global/pixi-pano360-remotely-controlled-motorized-head-mhpixi360/) synchronized with the timer of the camera (if the camera offers this function otherwise take manual shots with the remote of the camera). In this case:

  - Set up the number of photographs to be taken on your camera.
  
  - Set up the interval time on your rotating mount.
  
  - Start the process.
  
- To speed up the process with a mobile phone you can use a  mobile phone mount like the [monfrotto](https://www.manfrotto.com/global/pixi-pano360-remotely-controlled-motorized-head-mhpixi360/) or the [Insta360 Flow](https://www.insta360.com/product/insta360-flow) with the proprietary app. In this case:

  - Set up the app so that it will take a full 360 rotation.
  
  - Start the process.
  
\  
-->
  
<iframe width="560" height="315" src="https://www.youtube.com/embed/YHXYS1xEQrM?si=QA8Z0-8fIEz9qHDe" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
How To Create 360 Photos with insta360 Flow, under [Eat Sleep 360](https://eatsleep360.ck.page/), via [YouTube](https://www.youtube.com/watch?v=YHXYS1xEQrM) 

\
 
## Spherical panorama camera/360 camera setup and acquisition

Although these steps are specific to the Insta360 Pro 2, they remain easily applicable to other types of 360 cameras:

1. Position the tripod at the viewpoint where you want to take the photographs and make sure is levelled with the bubble.

2. Mount the camera on the tripod.

3. Turn on the camera, and turn on the wifi.

4. Turn on the Wifi (or Bluetooth if you are using another system) on your phone, find the camera and connect to it.

5. Open the [control camera App](https://www.insta360.com/download/insta360-pro2) and connect to it (for the Insta360 you can follow the tutorial on the app).

6. Keep the camera straight using a level function of the camera app.

7. Adjust the light setting on the app. Settings for acquiring well-lighted photographs are the same settings for standard DSRL cameras. You should be already familiar with these settings. If you need some help you can consult [this guideline](https://capturetheatlas.com/camera-settings/)

8. Start taking the first photographs. This will be a series of 6 photographs for mono viewing or 12 for stereo viewing.

Here is a quick video tutorial for general 360 camera shooting:

<iframe width="560" height="315" src="https://www.youtube.com/embed/wlOwvnYQT0k?si=g3-TW1pLlzgEfzl9" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
How to shoot panoramas with a 360 camera, under [under [Metareal](https://www.metareal.com/), via [YouTube](https://www.youtube.com/watch?v=wlOwvnYQT0k)



## Shooting tips

- Use a good-quality, strudy and slim tripod.

- Where possible, keep the sun on the side of the camera and do not position the camera directly looking at the sun.

- In all cases use a remote control or a dedicated app for taking photographs to avoid camera movements.

- Acquire the photographs in raw format as they contain more colour information. 


