---
title: 'Examples in Cultural Heritage'
teaching: 30
exercises: 0
---

:::::::::::::::::::::::::::::::::::::: questions 

- Lists projects with examples of digitisation using 360 degrees 
photography of Cultural Heritage

::::::::::::::::::::::::::::::::::::::::::::::::

Spherical panorama images have entered the Cultural Heritage realm since the beginning of this technique. This is because these photographs give the viewer the possibility to explore the surrounding of a certain environment with ease. Spherical panorama images are in fact one of the best tool to visualise a complete representation of a cultural environment at a specific point of where the photographs was taken. This is also enhanced when associated with Virtual Tours (not to be confused with 3D virtual tours which come from video-games techniques). In this section however we will concentrate only on a single spherical photograph digitaisation because the creation and the publication of 360 virtual tours, although it will be mention trought the lesson, is out of the scope of this workshop. The article:[*Panoramic 360◦ Sphere: Digitization and Mobilization of Cultural Heritage Site and Story Visualizing of History for Cultural Tourism, by Ylenia Cariani*](https://www.silvher.eu/2021/01/04/panoramic-360%E2%97%A6-sphere-digitization-and-mobilization-of-cultural-heritage-site-and-story-visualizing-of-history-for-cultural-tourism/) highlights why digitasation with spherical panorama has its benefit especially for Cultural Tourism

Here you can view some examples of the [UNESCO World Heritage Sites](https://www.p4panorama.com/gallery-categories/unesco-360-virtual-tours/).

A list of project that used a this technique as digitasation method is provided below:

<span style="color:red">
NICOLA PLEASE: Create a list similar to this:https://universityofbrighton.github.io/2023-exhibition-design/more-information.html
</span>


- Online 360: [Evaluation of an Online 360° Virtual Reality World Heritage Site During COVID-19](https://www.degruyter.com/document/doi/10.1515/opar-2020-0188/html)

- 


\





:::::::::::::::::::::::::::::::::::::: challenge 

Reflect on how the examples described could 
be applicable to the objects and
environments you would like to document.

List ideas where 360 might be a useful documentation
technology.


:::::::::::::::::::::
