---
title: 'Processing and Stitching'
teaching: 60
exercises: 0
---


:::::::::::::::::::::::::::::::::::::: questions 



- How 360 panoramas are  processed?


:::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives


- Shows how to processed and stitched 360 photo shooting.


<!-- - Advantages and disadvantages for the use of this techniques.-->

::::::::::::::::::::::::::::::::::::::::::::::::



## Processing and Stitching


### Dowloading and organizing images onto the computer
Once the images are acquired they will need to be saved on local disk in order to be processed. Each cameras has its own software to save the images. In this workshop we are going to use the Insta360 Pro2 [**stiching software**](https://www.insta360.com/download/insta360-pro2). For other types of 360 cameras please follow the specific instructions of each camera, however it will be usually  sufficient to download the images by connecting the camera via usb or by extracting the SD card from the camera and inserting it on a card reader to the PC.

Using a suitable name which reflects your project, transfer all images into a folder.

Good practice includes:

    ResourceIDifExistent_NameofObject_DateProcessedinFormatYY.MM.DD
    
Within this folder, create another one named images. Copy the images from the camera into the images folder.

\

The basic step to connect the Insta360 Pro2 camera can be followed on the video tutorial below or found on chapter one of the [Insta360 Pro2 Manual](https://data.d4science.org/shub/E_ZWY4eFRLK3JxQWdxU0lDb0pBV2VsZStzM0toVG1xRTJZZUVMd1VVZExpcDJHaElpWm41d0JTMFhJaU9Id0owWA==)

|   |
|---|
|<iframe width="560" height="315" src="https://www.youtube.com/embed/HEKvguHE8HM?si=7rLzOtexpkAoZVjG" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> |
| Insta360 Pro 2 Tutorial – Importing Files, under [Insta360](https://www.insta360.com/), via [YouTube](https://www.youtube.com/watch?v=HEKvguHE8HM) |



\
<!--[Insta360 Pro2 Editing Software](https://www.insta360.com/download/insta360-pro2)-->

### Stitching the images
The process of stitching images after have been acquired and downloaded to the computer also differ from software to software. Although not compulsory it is a good practice to learn the software that comes with the camera, especially when the camera is a professional one.

|   |
|---|
| <iframe width="560" height="315" src="https://www.youtube.com/embed/ZozZv_ONfi8?si=NFKpjsdrsJfhgW76" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> | 
| Insta360 Pro 2 Tutorial – Stitching 360 Photos in Stitcher, under [Insta360](https://www.insta360.com/), via [YouTube](https://www.youtube.com/watch?v=ZozZv_ONfi8) |





For a full process you can also follow the video below

|   |
|---|
| <iframe width="560" height="315" src="https://www.youtube.com/embed/SwzBG5F84Pc?si=JV-zwA1Tx8o8KG4V" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> | 
| Using the Insta360 pro 2, under [Joseph Farbrook](https://www.youtube.com/@josephfarbrook), via [YouTube](https://www.youtube.com/watch?v=SwzBG5F84Pc) |

\
